package com.hdclark.weddingbingo

object WeddingPrompts {
    private val labels = listOf(
        "👰 Veil needs fixing",
        "🤵 Tie gets straightened",
        "💍 Ring won’t slide",
        "💐 Bouquet held too high",
        "📸 ‘One more photo!’",
        "😭 Happy parent tears",
        "🥹 Guest gets misty-eyed",
        "😴 Kid looks exhausted",
        "👟 Fancy shoes abandoned",
        "🧦 Surprise silly socks",
        "🎀 Chair has a bow",
        "🌸 Petals everywhere",
        "🕯️ Candle refuses to light",
        "🎶 Entrance song swells",
        "👏 Applause starts early",
        "🤫 Someone shushes a row",
        "📱 Phone held too high",
        "📷 Group photo chaos",
        "🪑 Reserved-seat confusion",
        "🧥 Jacket comes off",
        "🌦️ Weather gets discussed",
        "☀️ ‘Perfect wedding weather’",
        "💨 Wind attacks the veil",
        "🦟 Bug crashes ceremony",
        "🐦 Bird has opinions",
        "👶 Tiny formal outfit",
        "🧒 Kid steals the show",
        "👧 Flower kid improvises",
        "💍 Ring bearer gets distracted",
        "🧸 Toy attends ceremony",
        "🍬 Emergency kid snack",
        "🥤 Fancy drink with straw",
        "🫧 Bubbles appear",
        "🎈 Balloon escapes",
        "🎉 Confetti sticks somewhere",
        "✨ Sparkly decoration overload",
        "🌿 Greenery on everything",
        "🪻 Flowers taller than guests",
        "🌹 Someone smells a flower",
        "💐 Bouquet gets rearranged",
        "📝 Vows on folded paper",
        "📖 Officiant flips pages",
        "😅 Name almost gets mixed up",
        "😂 Vow gets a big laugh",
        "🥹 Vow causes sniffles",
        "💬 ‘Best friend’ in vows",
        "❤️ ‘Forever’ gets mentioned",
        "🫶 ‘Soulmate’ gets mentioned",
        "🏡 ‘Build a life’ appears",
        "🌍 ‘Adventure together’ appears",
        "🎤 Microphone squeaks",
        "🔊 Speaker pops once",
        "🎵 Music starts slightly late",
        "🎼 Music stops awkwardly",
        "🚶 Processional speed mismatch",
        "👣 Someone misses their cue",
        "🙃 Someone stands too soon",
        "🪑 Everyone sits late",
        "👀 Guest watches the aisle",
        "😮 Big entrance reaction",
        "💋 Kiss gets huge cheers",
        "👏 Extra-long applause",
        "🎊 ‘They did it!’",
        "🔔 Bells or chimes",
        "🚪 Door opens dramatically",
        "🌳 Outdoor ceremony backdrop",
        "🏛️ Fancy arch or columns",
        "💒 Decorative wedding arch",
        "🧺 Basket of petals",
        "🪧 Cute wedding sign",
        "✍️ Guestbook station",
        "🖼️ Childhood photos displayed",
        "🕰️ Timeline sign",
        "🗺️ Seating chart puzzle",
        "🏷️ Place-card hunt",
        "🔢 Table-number confusion",
        "🪑 Someone swaps seats",
        "🤝 New relatives introduced",
        "🧑‍🤝‍🧑 ‘How do you know them?’",
        "😄 Same story told twice",
        "🗣️ Someone says ‘small world’",
        "📛 Someone forgets a name",
        "🤔 ‘Bride or groom side?’",
        "👋 Across-room wave",
        "🤳 Wedding selfie",
        "📸 Photo-booth pose",
        "🥸 Silly photo prop",
        "👑 Fake photo-booth crown",
        "🕶️ Giant novelty glasses",
        "🪄 Prop wand appears",
        "🍽️ Menu gets inspected",
        "🥖 Bread disappears instantly",
        "🧈 Butter packet struggle",
        "🥗 Someone skips the salad",
        "🥔 Potato gets praised",
        "🍝 Sauce threatens an outfit",
        "🥕 One vegetable survives",
        "🍰 Cake gets photographed first",
        "🧁 Cupcake tower spotted",
        "🍪 Cookie table admired",
        "🍬 Candy favour appears",
        "🍫 Chocolate disappears fast",
        "🍓 Fancy fruit garnish",
        "🍋 Lemon slice decoration",
        "☕ Coffee line forms",
        "🫖 Tea request causes search",
        "💧 Water glass mystery",
        "🥂 Sparkling-toast clink",
        "🧃 Kid gets juice upgrade",
        "🎂 Cake-cutting instructions",
        "🔪 Cake knife photo pose",
        "😏 Fake cake-smash threat",
        "😂 Cake bite gets cheers",
        "🍰 Frosting on a nose",
        "🧻 Napkin rescue mission",
        "🧼 Outfit stain inspection",
        "👜 Purse contains everything",
        "🩹 Someone needs a bandage",
        "🧷 Safety pin saves the day",
        "🪡 Clothing fix emergency",
        "💄 Mirror check before photo",
        "🪮 Hair gets re-pinned",
        "👔 Collar gets adjusted",
        "👗 Dress train gets carried",
        "🥿 Shoe comfort debate",
        "🧥 Someone guards coats",
        "🎤 Speech begins with ‘wow’",
        "📄 Speech notes unfold",
        "😬 Embarrassing story begins",
        "😂 Couple hides their faces",
        "👏 Toast gets applause",
        "🥹 Toast turns sentimental",
        "🧑‍🏫 Advice gets surprisingly serious",
        "💡 ‘Never go to bed angry’",
        "🕰️ ‘Feels like yesterday’",
        "👶 Childhood story appears",
        "🏫 School story appears",
        "🚗 Road-trip story appears",
        "📱 Dating-app joke appears",
        "💬 ‘I knew immediately’",
        "🤭 ‘Finally!’ gets said",
        "⌛ Joke about waiting",
        "🧡 ‘Welcome to the family’",
        "🥂 Everyone raises a glass",
        "🎶 First-dance song starts",
        "🕺 Carefully rehearsed spin",
        "💃 Dress twirl moment",
        "👣 Toe-stepping joke",
        "📸 Photographer circles dancers",
        "🥹 Parent dance gets tears",
        "🎵 DJ requests denied",
        "🎧 DJ says ‘make some noise’",
        "🙌 Hands go in the air",
        "👏 Clapping to the beat",
        "🕺 One fearless dance-floor hero",
        "💃 Dance circle forms",
        "🧒 Kid dominates dance floor",
        "👴 Older guest knows every move",
        "🧑‍🤝‍🧑 Conga-ish line forms",
        "🪩 Disco ball moment",
        "🎶 Singalong suddenly happens",
        "🎸 Air guitar appears",
        "🥁 Table drumming begins",
        "🎵 Someone requests a classic",
        "💐 Bouquet toss fake-out",
        "🙈 Bouquet dodged dramatically",
        "🙌 Bouquet catch celebration",
        "🪑 Chair moved for dancing",
        "👟 Dance shoes switched",
        "😮 Dance move surprises everyone",
        "😂 Coordinated move collapses",
        "📱 Dance video gets recorded",
        "🤳 Group selfie expands forever",
        "👋 Couple visits every table",
        "🫂 Hug lasts a while",
        "🤝 Handshake becomes a hug",
        "🥹 Goodbye gets emotional",
        "🎁 Gift table fills up",
        "💌 Card box gets admired",
        "🎀 Favour left on table",
        "🌙 Someone says ‘what a day’",
        "⌚ Someone checks the time",
        "🚕 Ride-home plans discussed",
        "🧥 Missing jacket search",
        "📱 Missing phone panic",
        "👓 Missing glasses search",
        "🧒 Sleepy kid gets carried",
        "🌸 Flower taken as souvenir",
        "🍰 Extra cake gets offered",
        "📦 Leftovers get negotiated",
        "👋 Ten-minute goodbye",
        "❤️ Couple looks ridiculously happy",
        "🎉 Someone declares ‘best wedding!’"
    )

    val all: List<BingoPrompt> = labels.mapIndexed { index, label ->
        BingoPrompt(id = "wedding-${index + 1}", label = label)
    }
}
